### ISSUE TITLE
Amazon S3 Media Source not in Package Manager

### ISSUE THREAD

**Issue by cjholowatyj** [modxcms/aws-s3-media-source#19]
The README suggests that this package can be found and installed from Package Manager, but I'm not seeing it my package manager when I search for 'aws', 's3', 'media' or other derivations of the name of this package. (I'm on Revo 2.6.1)

Is this a package I should be able to find in Package Manager?

The reason I ask is that I'm not having any success with the built-in s3 bucket media source option in MODX, and I'm hoping this is not the same (updated or whatever).

**Comment by garryn** [comment]
As far as I know, it is not yet available in Package Management but you can grab the latest version of the transport package (to upload and install via Package Management) in the _packages directory in the repository.

This version does solve issues found in the built-in media source (specifically, it has the latest authentication method required for newer S3 buckets/locations).

The current version is here: https://github.com/modxcms/aws-s3-media-source/blob/master/_packages/awss3mediasource-0.10.0-pl.transport.zip

**Comment by cjholowatyj** [comment]
Thanks @garryn that is very good to know! I'm going to attempt the install from the transport package! I wonder if it might be worth amending the README (at least temporarily) to reflect the fact that it is soon to be but not yet in the Package Manager? Certainly threw me for a loop! haha
