### ISSUE TITLE
Don't hard-code the S3 URL. If not hard-coded, it's also compatible with Digital Ocean Spaces

### ISSUE THREAD

**Issue by muzzwood** [modxcms/aws-s3-media-source#20]
I have added `'endpoint' =>'https://sgp1.digitaloceanspaces.com'` 
into line 54 of model/aws3smediasource.class.php like this:

```
$this->driver = new Aws\S3\S3Client([
    'version' => 'latest',
    'endpoint'=> 'https://sgp1.digitaloceanspaces.com',
    'region' => $this->xpdo->getOption('region', $this->properties, ''),
    'credentials' => [
        'key' => $this->xpdo->getOption('key', $this->properties, ''),
        'secret' => $this->xpdo->getOption('secret_key', $this->properties, '')
    ]
]);
```

and now it works with Digital Ocean Spaces! 
(of course you need to change the "sgp1" sub-domain to whatever you're using.)

**Comment by jaygilmore** [comment]
Where is the `endpoint` defined in the code, in general? Could this not be made a system setting like the other properties here? It seems like a fairly simple change that could open this up to work with any S3-based API storage solution.
